[package]
name = "token-balances"
version = "0.1.0"
edition = "2021"

[lib]
name = "token_balances"
crate-type = ["cdylib"]

[dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
itertools = "0.12.1"
rustc-hash = "2.1.2"
serde = "1.0.204"
serde_qs = "0.13.0"
substreams = "0.5.22"
substreams-ethereum = "0.9.9"
tiny-keccak = { version = "2.0", features = ["keccak"] }
tycho-substreams = "0.8.0"

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["custom"] }
